// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

/// Cross-check that proofs generated by lottery/build_v2_proofs.py verify against the on-chain leaf
/// format the contract uses (keccak256(bytes.concat(keccak256(abi.encode(address))))). This proves the
/// Python proof generator and the Solidity claim path agree end-to-end.
contract ProofGenCrossCheck is Test {
    string constant DIR = "test/fixtures/v2/";

    function _leaf(address a) internal pure returns (bytes32) {
        return keccak256(bytes.concat(keccak256(abi.encode(a))));
    }

    function test_PythonProofsVerifyOnChain() public view {
        bytes32 root = vm.parseJsonBytes32(vm.readFile(string.concat(DIR, "genesis.meta.json")), ".setRoot");
        address[4] memory addrs = [
            address(uint160(0x1000)),
            address(uint160(0x1001)),
            address(uint160(0x1002)),
            address(uint160(0x1003))
        ];
        for (uint256 i = 0; i < 4; i++) {
            string memory f = string.concat(DIR, "proof/", vm.toLowercase(vm.toString(addrs[i])), ".json");
            bytes32[] memory proof = vm.parseJsonBytes32Array(vm.readFile(f), ".proof");
            assertTrue(MerkleProof.verify(proof, root, _leaf(addrs[i])), "python proof must verify on-chain");
        }
        // a wrong address must NOT verify against another's proof
        bytes32[] memory p0 =
            vm.parseJsonBytes32Array(vm.readFile(string.concat(DIR, "proof/", vm.toLowercase(vm.toString(addrs[0])), ".json")), ".proof");
        assertFalse(MerkleProof.verify(p0, root, _leaf(addrs[1])), "proof is address-specific");
    }
}
